version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/main/src
      - /main/node_modules
    command: yarn dev
